### ISSUE TITLE
Microsoft on `srcset` support and the Picturefill situation

### ISSUE THREAD

**Issue by eeeps** [ResponsiveImagesCG/newsletters#216]
blogs.windows.com/msedgedev/2015/06/08/introducing-srcset-responsive-images-in-microsoft-edge/

The Good: `srcset` + `x` descriptors are shipping and `w` descriptors, `sizes`, and `picture`, are on the roadmap.
The Bad: shipping without `currentSrc`, because Picturefill
Simply Amazing:
> We reached this estimate by crawling a random set of 500 thousand sites and found that 3% of the sites were actively using Picturefill. If we extrapolate that to the estimated 978 million active sites that results in approximately 29 million sites. Based on this we can safely conclude that there are millions of sites utilizing picturefill.

**Comment by yoavweiss** [comment]
The numbers are not accurate. I believe @gregwhitworth corrected that it's
0.03%, rather than 3%

**Comment by eeeps** [comment]
That’s quite the difference. Still, 300,000... not *too* shabby.

**Comment by gregwhitworth** [comment]
Yep, my bad - sorry about that. So used to doing the calcs by hand and when Excel did them I read it as 3 percent instead of not even 1 percent. And no it's not shabby, but not quite as large. In all honesty, the number count isn't as impressive as who is using it, it's some of the largest sites on the Web.
